---
- name: Configure Repository
  yum_repository:
    name: kubernetes
    description: kube
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: True
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install Packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - kubeadm

- name: Disable SELinux
  selinux:
    policy: disabled
    state: disabled

- name: Copy Kubeadm Config
  copy:
    src: 09-kubeadm.conf
    dest: /etc/systemd/system/kubelet.service.d/09-kubeadm.conf
    owner: root
    group: root
    mode: 0644

- name: Restart kubelet and daemon reload
  systemd:
    daemon_reload: True
    name: kubelet
    state: restarted
    enabled: True
