---
- name: Install Packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - docker
    - NetworkManager
    - NetworkManager-glib
    - nm-connection-editor.x86_64
    - libsemanage-python
    - policycoreutils-python
    - parted
    - e2fsprogs
    - vim
